ALTER TABLE users ADD COLUMN status VARCHAR(50);
UPDATE users SET status = 'ACTIVE' WHERE status IS NULL;
ALTER TABLE users ALTER COLUMN status SET NOT NULL;
ALTER TABLE users ALTER COLUMN status SET DEFAULT 'PENDING_VERIFICATION';
